### ISSUE TITLE
Move IMT crate from zk-kit to zk-kit.rust

### ISSUE THREAD

**Issue by cedoor** [privacy-scaling-explorations/zk-kit.rust#3]
**Describe the package you'd like**

An IMT implementation in Rust has already been added to the [zk-kit repository](https://github.com/privacy-scaling-explorations/zk-kit/pull/134). However, since the Rust crates should stay in this repository now, the code should be moved here.

**Comment by cedoor** [comment]
cc @Arch0125

**Comment by Arch0125** [comment]
Pushing the changes here soon
