### ISSUE TITLE
Move pmtree implementation from RLN to zk-kit.rust

### ISSUE THREAD

**Issue by cedoor** [privacy-scaling-explorations/zk-kit.rust#4]
**Describe the package you'd like**

[`pmtree`](https://github.com/Rate-Limiting-Nullifier/pmtree) (Persistent Merkle Tree) is an optimized, sparse, fixed-size Merkle tree implementation in Rust. The code is currently in the RLN repository. It will, however, be moved to ZK-Kit as part of a general effort by PSE to move reusable libraries and implementation to one place.

**Comment by cedoor** [comment]
@curryrasul are you the author of this lib? Would you like to move that crate yourself?

**Comment by wiasliaw** [comment]
Hi @cedoor, can I get this issue?

**Comment by cedoor** [comment]
Hey @wiasliaw, of course :) I'll assign it to you 👍🏽
