### ISSUE TITLE
For true non-membership, verify_proof returns false instead of true

### ISSUE THREAD

**Issue by 0xDatapunk** [privacy-scaling-explorations/zk-kit.rust#58]
in smt, to prove non-membership of a key without matching_entry, should I expect the verify function to return false or true?
https://github.com/privacy-scaling-explorations/zk-kit.rust/blob/8d63b9fb17e8bfdceb99d50b9f92538188fd266d/crates/smt/src/smt.rs#L363

As an example, let's start with a tree with [0101,'a'], [0111,'b']. assuming hash is concatenation, and we want to proof 1111, create_proof gives:
MerkleProof {
    entry_response: EntryResponse {
        entry: vec![Node::Str("1111".to_string())],
        matching_entry: None,
        siblings: vec![Node::Str("0101,a,1,0111,b,1".to_string())],
    },
    root: Node::Str("0101,a,1,0111,b,1".to_string()),
    membership: false,
}
 
Now verify_proof, would use zero node to produce a root Node::Str("0101,a,1,0111,b,1,0".to_string()), so verify_proof returns false. 
My understanding is we should expect true, since the MerkleProof says membership is false

**Comment by cedoor** [comment]
cc @waddaboo

**Comment by cedoor** [comment]
@waddaboo could you add a comment here? So that I can assign this task to you.

**Comment by waddaboo** [comment]
Not sure if it's still required but here's a comment :)

**Comment by cedoor** [comment]
@waddaboo yes, thank you so much for the PR 🙏🏽
