### ISSUE TITLE
membership field is not explicitly checked

### ISSUE THREAD

**Issue by 0xDatapunk** [privacy-scaling-explorations/zk-kit.rust#59]
https://github.com/privacy-scaling-explorations/zk-kit.rust/blob/8d63b9fb17e8bfdceb99d50b9f92538188fd266d/crates/smt/src/smt.rs#L363

membership field is not used explicitly in verify_proof, so supposedly one can flip membership.
For example, assuming 011111 is not in the tree, and create_proof gives:
MerkleProof {
    entry_response: EntryResponse {
        entry: vec![Node::Str("011111".to_string())],
        matching_entry: Some(vec![Node::Str("0111".to_string()), Node::Str("b".to_string()), Node::Str("1".to_string())]),
        siblings: vec![Node::Str("0101,a,1".to_string())],
    },
    root: Node::Str("0101,a,1,0111,b,1".to_string()),
    membership: false,
}

Now if I change membership to true, verify_proof still passes. This behavior is very confusing.

**Comment by waddaboo** [comment]
@cedoor thanks for the tag! Though I'm not very sure on how to fix it, do you mind giving me some pointers?

**Comment by 0xDatapunk** [comment]
do it make sense to do something to this effect?
change
`if root == merkle_proof.root {`
to 
`if merkle_proof.membership == (root == merkle_proof.root) {`

**Comment by waddaboo** [comment]
@0xDatapunk Thank you for the suggestion! After implementing this, it seems to have solve issue #58 as well.
