### ISSUE TITLE
Create a crate for SMT based on JS implementation

### ISSUE THREAD

**Issue by cedoor** [privacy-scaling-explorations/zk-kit.rust#8]
**Describe the package you'd like**

The SMT (Sparse Merkle Tree) implemented in [JS](https://github.com/privacy-scaling-explorations/zk-kit/tree/main/packages/smt) is an optimized SPT proposed by [Vitalik](https://ethresear.ch/t/optimizing-sparse-merkle-trees/3751) and further optimized by the [Iden3 team](https://docs.iden3.io/publications/pdfs/Merkle-Tree.pdf). It efficiently enables the generation of proof of membership and non-membership.

It is worth checking whether an implementation in Rust already exists.

**Comment by waddaboo** [comment]
Hi! I would like to work on this issue :)

**Comment by vplasencia** [comment]
Hey Han! I just assigned you this issue. Feel free to ask any questions you may have.
